const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Fade,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.EightDir.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{Text: 0},
	{Tween: 0},
	{button: 0},
	{Touch: 0},
	{main_background: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Flash: 0},
	{player: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{bullet: 0},
	{ZombieHealth: 0},
	{movement: 0},
	{Pathfinding: 0},
	{zombie: 0},
	{Fade: 0},
	{explosion: 0},
	{Anchor: 0},
	{TextScore: 0},
	{start_background: 0},
	{textGameOver: 0},
	{heart1: 0},
	{heart2: 0},
	{heart3: 0},
	{Audio: 0},
	{arrowDown: 0},
	{arrowUp: 0},
	{arrowleft: 0},
	{fire: 0},
	{arrowRight: 0},
	{gameOver: 0},
	{restartButton: 0},
	{playerHealth: 0},
	{ZombieSpeed: 0},
	{Score: 0}
];

self.InstanceType = {
	Text: class extends self.ITextInstance {},
	button: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	main_background: class extends self.ITiledBackgroundInstance {},
	player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	bullet: class extends self.ISpriteInstance {},
	zombie: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	TextScore: class extends self.ITextInstance {},
	start_background: class extends self.ITiledBackgroundInstance {},
	textGameOver: class extends self.ITextInstance {},
	heart1: class extends self.ISpriteInstance {},
	heart2: class extends self.ISpriteInstance {},
	heart3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	arrowDown: class extends self.ISpriteInstance {},
	arrowUp: class extends self.ISpriteInstance {},
	arrowleft: class extends self.ISpriteInstance {},
	fire: class extends self.ISpriteInstance {},
	arrowRight: class extends self.ISpriteInstance {},
	gameOver: class extends self.ISpriteInstance {},
	restartButton: class extends self.ISpriteInstance {}
}